### ISSUE TITLE
TypeError messages

### ISSUE THREAD

**Issue by Ezka77** [jcorporation/myMPD#1025]
myMPD version: devel 10.3.2 commit bee13683

I get this error message: 
`TypeError: text is undefined (https://192.168.0.100/js/combined.js: 6474)`

When a song reaches the end in the queue panel and when I switch to another panel:

![image](https://github.com/jcorporation/myMPD/assets/1818604/05cee7cb-3fea-4547-94e9-663c123a9f7f)

I think it also breaks the line-progress-bar-thing 😁 

and in the same idea I also get this one when I click on "toggle play"

![image](https://github.com/jcorporation/myMPD/assets/1818604/f0c64062-d207-4210-8e76-74434222e59b)

NB: Webradios doesn't have theses issues 

**Server plattform (please complete the following information):**
 - OS: alpine linux
 - OS version: stable
 - Platform: x86_64
 - MPD version: 23.13

**Client plattform (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Browser: firefox 
 - Browser version: 113.0.1

I know it's a bug report, but I have to say that I already like this new version of the UI 👏 👍

**Comment by jcorporation** [comment]
I can not reproduce your issue.
Are there more errors in the Web Developer Tools Console?

**Comment by Ezka77** [comment]
I've this kind of messages in the browser console using the HEAD of devel:
For the first TypeError:
```
18:19:25,787 DEBUG: Websocket notification: {"jsonrpc":"2.0","method":"update_state","params":{"state":"play","volume":70,"songPos":8,"elapsedTime":0,"totalTime":199,"currentSongId":10,"kbitrate":128,"queueLength":12,"queueVersion":18,"nextSongPos":9,"nextSongId":11,"lastSongId":9,"partition":"default","AudioFormat":{"sampleRate":44100,"bits":224,"channels":2},"updateState":0,"updateCacheState":false,"lastError":""}} combined.js:4291:30
18:19:25,787 DEBUG: Send API request: MYMPD_API_PLAYER_CURRENT_SONG combined.js:4291:30
18:19:25,787 DEBUG: Set mediaSession.playbackState to playing combined.js:4291:30
18:19:25,957 DEBUG: Got API response of type: MYMPD_API_PLAYER_CURRENT_SONG combined.js:4291:30
18:19:25,957 DEBUG: Calling parseCurrentSong combined.js:4291:30
18:19:25,958 DEBUG: getData: "uri":"/albumart?offset=0&uri=Caroline%20Polachek%2FDesire%2C%20I%20Want%20to%20Turn%20Into%20You%2F08%20Blood%20and%20Butter.m4a" 3 combined.js:4291:30
18:19:25,962 Uncaught TypeError: text is undefined
    elCreateText https://192.168.0.100/js/combined.js:6474
    getMBtagLink https://192.168.0.100/js/combined.js:8774
    addMusicbrainzFields https://192.168.0.100/js/combined.js:8799
    setPlaybackCardTags https://192.168.0.100/js/combined.js:18749
    parseCurrentSong https://192.168.0.100/js/combined.js:18666
    onreadystatechange https://192.168.0.100/js/combined.js:13215
combined.js:6474:9
```

And here for the second one:
```
18:14:44,394 DEBUG: Browser tab gots the focus -> update player state combined.js:4291:30
18:14:44,394 DEBUG: Send API request: MYMPD_API_PLAYER_STATE combined.js:4291:30
18:14:44,459 DEBUG: getData: "href":"{"cmd": "clickPlay", "options": []}" combined.js:4291:30
18:14:44,462 Uncaught TypeError: uri is undefined
    isStreamUri https://192.168.0.100/js/combined.js:9490
    clickPlay https://192.168.0.100/js/combined.js:9095
    parseCmd https://192.168.0.100/js/combined.js:7771
    parseCmdFromJSON https://192.168.0.100/js/combined.js:7723
    appInit https://192.168.0.100/js/combined.js:24019
combined.js:9490:9
```

**Comment by Ezka77** [comment]
I've check with another album both are tagged with MBZ, same error:
```
18:29:52,444 DEBUG: Browser tab gots the focus -> update player state combined.js:4291:30
18:29:52,445 DEBUG: Send API request: MYMPD_API_PLAYER_STATE combined.js:4291:30
18:29:52,538 DEBUG: getData: "href":"[object Object]" combined.js:4291:30
18:29:52,540 DEBUG: Send API request: MYMPD_API_DATABASE_ALBUM_DETAIL combined.js:4291:30
18:29:52,616 DEBUG: Got API response of type: MYMPD_API_PLAYER_STATE combined.js:4291:30
18:29:52,616 DEBUG: Calling parseState combined.js:4291:30
18:29:52,616 DEBUG: Set mediaSession.playbackState to playing combined.js:4291:30
18:29:52,764 DEBUG: Got API response of type: MYMPD_API_DATABASE_ALBUM_DETAIL combined.js:4291:30
18:29:52,765 DEBUG: Calling parseAlbumDetails combined.js:4291:30
18:29:52,766 Uncaught TypeError: text is undefined
    elCreateText https://192.168.0.100/js/combined.js:6474
    getMBtagLink https://192.168.0.100/js/combined.js:8774
    addMusicbrainzFields https://192.168.0.100/js/combined.js:8799
    parseAlbumDetails https://192.168.0.100/js/combined.js:15171
    onreadystatechange https://192.168.0.100/js/combined.js:13215
combined.js:6474:9
18:29:54,082 DEBUG: Got websocket pong combined.js:4291:30
```

**Comment by jcorporation** [comment]
Please test if above commit fixes your issues.

**Comment by jcorporation** [comment]
Please attach your mpd and myMPD configuration (enabled tags are interesting). I would like to reproduce the issue.

**Comment by Ezka77** [comment]
The error on "toggle play" button seems fixed, but the first TypeError is still here.

For MPD, with all my finesse :grin:, I've enable all the metadata that I can find:
```
metadata_to_use "albumartist,artist,album,title,track,name,genre,date,disc,albumartistsort,MUSICBRAINZ_ALBUMARTISTID,MUSICBRAINZ_ARTISTID,MUSICBRAINZ_RELEASETRACKID,MUSICBRAINZ_RELEASETRACKID"
```

Here the full configuration file:
[mpd.log](https://github.com/jcorporation/myMPD/files/11585385/mpd.log) 

And on mympd same idea:
![mympd settings](https://github.com/jcorporation/myMPD/assets/1818604/022a309d-c384-4192-9855-0948b3075d58)

I've try keeping only the "artist" tag in mympd UI but still I get the same issue even with no tags enabled (but I like this clean UI though)
![no tags](https://github.com/jcorporation/myMPD/assets/1818604/9fafc33e-f944-4a59-88b3-6cd2e6a385f6)

**Comment by jcorporation** [comment]
Same error in the browser console? The JavaScript stacktrace is always interesting. Any errors in the myMPD log (set it to debug)?

Occurs this error also in other browsers?

**Comment by Ezka77** [comment]
Server side a JSON message seems truncated, the uri part (if the log is not truncated itself):
```
May 29 09:39:53 sparrow daemon.debug mympd: "default": Got API response for id "32"
May 29 09:39:53 sparrow daemon.debug mympd: "default": Sending response to conn_id 32 (length: 4336): {"jsonrpc":"2.0","id":0,"result":{"method":"MYMPD_API_DATABASE_ALBUM_DETAIL","data":[{"Type": "song","Track":"1","Title":"Welcome to My Island","Album":"Desire, I Want to Turn Into You","AlbumArtist":["Caroline Polachek"],"Date":"2023-04-23","Name":"-","Disc":"1","Duration":233,"LastModified":1683314364,"uri":"Caroline Polachek/Desire, I Want to Turn Into You/01 Welcome to My Island.m4a"},{"Type": "song","Track":"2","Title":"Pretty in Possible","Album":"Desire, I Want to Turn Into You","AlbumArtist":["Caroline Polachek"],"Date":"2023-04-23","Name":"-","Disc":"1","Duration":216,"LastModified":1683314364,"uri":"Caroline Polachek/Desire, I Want to Turn Into You/02 Pretty in Possible.m4a"},{"Type": "song","Track":"3","Title":"Bunny Is a Rider","Album":"Desire, I Want to Turn Into You","AlbumArtist":["Caroline Polachek"],"Date":"2023-04-23","Name":"-","Disc":"1","Duration":194,"LastModified":1683314364,"uri":"Caroline Polachek/De
May 29 09:39:53 sparrow daemon.debug mympd: Sending 4336 bytes to 32
May 29 09:40:01 sparrow daemon.debug mympd: "default": Websocket message (18): ping
```

And the corresponding message in Firefox JS console:
```
09:38:15,722 Uncaught TypeError: text is undefined
    elCreateText https://192.168.0.100/js/combined.js:6474
    getMBtagLink https://192.168.0.100/js/combined.js:8775
    addMusicbrainzFields https://192.168.0.100/js/combined.js:8800
    parseAlbumDetails https://192.168.0.100/js/combined.js:15175
    onreadystatechange https://192.168.0.100/js/combined.js:13219
combined.js:6474:9
```
And with Chrome the error seems to have some more intel about lenght:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at elCreateText (combined.js:6474:14)
    at getMBtagLink (combined.js:8775:16)
    at addMusicbrainzFields (combined.js:8800:31)
    at parseAlbumDetails (combined.js:15175:21)
    at ajaxRequest.onreadystatechange (combined.js:13219:17)
```

**Comment by jcorporation** [comment]
Log is truncated to 1023 bytes. The browser should show the full response in the network tab.

On a truncated response, the browser should throw a json parser error.

**Comment by Ezka77** [comment]
Right the response is not truncated:
```
{"jsonrpc":"2.0","id":0,"result":{"method":"MYMPD_API_DATABASE_ALBUM_DETAIL","data":[{"Type": "song","Track":"1","Title":"Welcome to My Island","Album":"Desire, I Want to Turn Into You","AlbumArtist":["Caroline Polachek"],"Date":"2023-04-23","Name":"-","Disc":"1","Duration":233,"LastModified":1683314364,"uri":"Caroline Polachek/Desire, I Want to Turn Into You/01 Welcome to My Island.m4a"},{"Type": "song","Track":"2","Title":"Pretty in Possible","Album":"Desire, I Want to Turn Into You","AlbumArtist":["Caroline Polachek"],"Date":"2023-04-23","Name":"-","Disc":"1","Duration":216,"LastModified":1683314364,"uri":"Caroline Polachek/Desire, I Want to Turn Into You/02 Pretty in Possible.m4a"},{"Type": "song","Track":"3","Title":"Bunny Is a Rider","Album":"Desire, I Want to Turn Into You","AlbumArtist":["Caroline Polachek"],"Date":"2023-04-23","Name":"-","Disc":"1","Duration":194,"LastModified":1683314364,"uri":"Caroline Polachek/Desire, I Want to Turn Into You/03 Bunny Is a Rider.m4a"},{"Type": "song","Track":"4","Title":"Sunset","Album":"Desire, I Want to Turn Into You","AlbumArtist":["Caroline Polachek"],"Date":"2023-04-23","Name":"-","Disc":"1","Duration":163,"LastModified":1683314364,"uri":"Caroline Polachek/Desire, I Want to Turn Into You/04 Sunset.m4a"},{"Type": "song","Track":"5","Title":"Crude Drawing of an Angel","Album":"Desire, I Want to Turn Into You","AlbumArtist":["Caroline Polachek"],"Date":"2023-04-23","Name":"-","Disc":"1","Duration":209,"LastModified":1683314364,"uri":"Caroline Polachek/Desire, I Want to Turn Into You/05 Crude Drawing of an Angel.m4a"},{"Type": "song","Track":"6","Title":"I Believe","Album":"Desire, I Want to Turn Into You","AlbumArtist":["Caroline Polachek"],"Date":"2023-04-23","Name":"-","Disc":"1","Duration":247,"LastModified":1683314364,"uri":"Caroline Polachek/Desire, I Want to Turn Into You/06 I Believe.m4a"},{"Type": "song","Track":"7","Title":"Fly to You","Album":"Desire, I Want to Turn Into You","AlbumArtist":["Caroline Polachek"],"Date":"2023-04-23","Name":"-","Disc":"1","Duration":245,"LastModified":1683314364,"uri":"Caroline Polachek/Desire, I Want to Turn Into You/07 Fly to You.m4a"},{"Type": "song","Track":"8","Title":"Blood and Butter","Album":"Desire, I Want to Turn Into You","AlbumArtist":["Caroline Polachek"],"Date":"2023-04-23","Name":"-","Disc":"1","Duration":267,"LastModified":1683314364,"uri":"Caroline Polachek/Desire, I Want to Turn Into You/08 Blood and Butter.m4a"},{"Type": "song","Track":"9","Title":"Hopedrunk Everasking","Album":"Desire, I Want to Turn Into You","AlbumArtist":["Caroline Polachek"],"Date":"2023-04-23","Name":"-","Disc":"1","Duration":199,"LastModified":1683314364,"uri":"Caroline Polachek/Desire, I Want to Turn Into You/09 Hopedrunk Everasking.m4a"},{"Type": "song","Track":"10","Title":"Butterfly Net","Album":"Desire, I Want to Turn Into You","AlbumArtist":["Caroline Polachek"],"Date":"2023-04-23","Name":"-","Disc":"1","Duration":276,"LastModified":1683314364,"uri":"Caroline Polachek/Desire, I Want to Turn Into You/10 Butterfly Net.m4a"},{"Type": "song","Track":"11","Title":"Smoke","Album":"Desire, I Want to Turn Into You","AlbumArtist":["Caroline Polachek"],"Date":"2023-04-23","Name":"-","Disc":"1","Duration":177,"LastModified":1683314364,"uri":"Caroline Polachek/Desire, I Want to Turn Into You/11 Smoke.m4a"},{"Type": "song","Track":"12","Title":"Billions","Album":"Desire, I Want to Turn Into You","AlbumArtist":["Caroline Polachek"],"Date":"2023-04-23","Name":"-","Disc":"1","Duration":297,"LastModified":1683314364,"uri":"Caroline Polachek/Desire, I Want to Turn Into You/12 Billions.m4a"}],"bookletPath":"","images": ["/browse/music/Caroline Polachek/Desire, I Want to Turn Into You/cover.jpg"],"embeddedImageCount":0,"returnedEntities":12,"Artist":["Caroline Polachek","Caroline Polachek feat. Grimes and Dido"],"Album":"Desire, I Want to Turn Into You","AlbumArtist":["Caroline Polachek"],"AlbumArtistSort":["Polachek, Caroline"],"Genre":["-"],"Date":"2023-04-23","Disc":"1","MUSICBRAINZ_ARTISTID":["d8f43dc5-4613-48ac-8c23-a62b82f8c67a"],"MUSICBRAINZ_ALBUMARTISTID":["d8f43dc5-4613-48ac-8c23-a62b82f8c67a"],"Duration":2723,"LastModified":1683314364,"uri":"Caroline Polachek/Desire, I Want to Turn Into You/01 Welcome to My Island.m4a","Discs":1,"SongCount":12,"lastPlayedSong":{"time":0,"uri":""}}}
```

Here the full JS log if it helps, quite easier to save it with Chrome (or I didn't find the right way to do it with firefox):
[mympd_errors.log](https://github.com/jcorporation/myMPD/files/11590222/mympd_errors.log)

and the debug log on mympd server:
[mympd_server.log](https://github.com/jcorporation/myMPD/files/11590245/mympd_server.log)

**Comment by jcorporation** [comment]
I could replicate your issue, it occurs only if the MUSICBRAINZ_ALBUMID tag is not enabled. Above commit fixes it in my environment.

Please test.

**Comment by Ezka77** [comment]
Work for me too 👍 nice job !
