### ISSUE TITLE
combined.js:23106 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'views')

### ISSUE THREAD

**Issue by d3xt3r01** [jcorporation/myMPD#1399]
myMPD version: 19.0.1

**Describe the bug**

Interface gets stuck at `Initializing myMPD`.
Interface works if I go to `https://mympd.local.lan/#%7B%22card%22%3A%22Queue%22%2C%22tab%22%3A%22Current%22%2C%22offset%22%3A0%2C%22limit%22%3A1000%2C%22filter%22%3A%22any%22%2C%22sort%22%3A%7B%22tag%22%3A%22Priority%22%2C%22desc%22%3Afalse%7D%2C%22tag%22%3A%22%22%2C%22search%22%3A%22%22%7D`

Interface also seems to work if I clear /var/lib/mpd in the container then stops working again.

**To Reproduce**

I go to https://mympd.local.lan/

**Expected behavior**

Interface to show up

**Server platform (please complete the following information):**
 - docker ghcr.io/jcorporation/mympd/mympd:19.0.1
 - 
**Client platform (please complete the following information):**
  Windows chrome

**Debug logs**

Browser error console
```
Navigated to https://mympd.local.lan/
mympd.local.lan/:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input id=​"modalEnterPinPinInput" class=​"form-control" type=​"password" autocomplete=​"off">​
utils.js:1 Could not establish connection. Receiving end does not exist. ahmkjjgdligadogjedmnogbpbcpofeeo {}
utils.js:1 Could not establish connection. Receiving end does not exist. jaekigmcljkkalnicnjoafgfjoefkpeg {}
utils.js:1 Could not establish connection. Receiving end does not exist. noogafoofpebimajpfpamcfhoaifemoa {}
utils.js:1 No suspender extension installed
combined.js:14361 DEBUG: Session expired: 0
combined.js:14359 ERROR: Locale "en-GB" not defined
logLog @ combined.js:14359
logError @ combined.js:14388
setLocale @ combined.js:14083
parseSettings @ combined.js:24524
(anonymous) @ combined.js:30166
checkAPIresponse @ combined.js:5974
sendAPIpartition @ combined.js:5920
await in sendAPIpartition
sendAPI @ combined.js:5789
appInitStart @ combined.js:30165
(anonymous) @ combined.js:30452Understand this errorAI
combined.js:14361 DEBUG: getData: "locale":"undefined"
combined.js:14361 DEBUG: Columns for viewPlayback: [object Object]
combined.js:14361 DEBUG: getData: "viewMode":"undefined"
combined.js:14361 DEBUG: Columns for viewSearch: [object Object]
combined.js:14361 DEBUG: getData: "viewMode":"undefined"
combined.js:14361 DEBUG: Columns for viewQueueCurrent: [object Object]
combined.js:14361 DEBUG: getData: "viewMode":"undefined"
combined.js:14361 DEBUG: Columns for viewQueueLastPlayed: [object Object]
combined.js:14361 DEBUG: getData: "viewMode":"undefined"
combined.js:14361 DEBUG: Columns for viewQueueJukeboxSong: [object Object]
combined.js:14361 DEBUG: getData: "viewMode":"undefined"
combined.js:14361 DEBUG: Columns for viewQueueJukeboxAlbum: [object Object]
combined.js:14361 DEBUG: getData: "viewMode":"undefined"
combined.js:14361 DEBUG: Columns for viewBrowsePlaylistDetail: [object Object]
combined.js:14361 DEBUG: getData: "viewMode":"undefined"
combined.js:14361 DEBUG: Columns for viewBrowseFilesystem: [object Object]
combined.js:14361 DEBUG: getData: "viewMode":"undefined"
combined.js:14361 DEBUG: Columns for viewBrowseDatabaseTagList: [object Object]
combined.js:14361 DEBUG: getData: "viewMode":"undefined"
combined.js:14361 DEBUG: Columns for viewBrowseDatabaseAlbumList: [object Object]
combined.js:14361 DEBUG: getData: "viewMode":"undefined"
combined.js:14361 DEBUG: Columns for viewBrowseDatabaseAlbumDetail: [object Object]
4combined.js:14361 DEBUG: getData: "viewMode":"undefined"
combined.js:23106 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'views')
    at appGoto (combined.js:23106:39)
    at appRoute (combined.js:23232:13)
    at parseSettings (combined.js:24744:9)
    at combined.js:30166:9
    at checkAPIresponse (combined.js:5974:13)
    at sendAPIpartition (combined.js:5920:5)
appGoto @ combined.js:23106
appRoute @ combined.js:23232
parseSettings @ combined.js:24744
(anonymous) @ combined.js:30166
checkAPIresponse @ combined.js:5974
sendAPIpartition @ combined.js:5920
await in sendAPIpartition
sendAPI @ combined.js:5789
appInitStart @ combined.js:30165
(anonymous) @ combined.js:30452
```

myMPD debug log
```
mympd-1  | DEBUG    webserver       New connection id "3" from 172.16.1.2, connections: 3
mympd-1  | INFO     webserver       HTTP request (3): GET /
mympd-1  | DEBUG    webserver       Set connection 3 to is_draining
mympd-1  | INFO     webserver       HTTP connection "3" closed
mympd-1  | DEBUG    webserver       New connection id "4" from 172.16.1.2, connections: 3
mympd-1  | INFO     webserver       HTTP request (4): GET /css/combined.css
mympd-1  | DEBUG    webserver       Set connection 4 to is_draining
mympd-1  | INFO     webserver       HTTP connection "4" closed
mympd-1  | DEBUG    webserver       New connection id "5" from 172.16.1.2, connections: 3
mympd-1  | INFO     webserver       HTTP request (5): GET /assets/MaterialIcons-Regular.woff2
mympd-1  | DEBUG    webserver       Set connection 5 to is_draining
mympd-1  | INFO     webserver       HTTP connection "5" closed
mympd-1  | DEBUG    webserver       New connection id "6" from 172.16.1.2, connections: 3
mympd-1  | INFO     webserver       HTTP request (6): GET /js/combined.js
mympd-1  | DEBUG    webserver       Set connection 6 to is_draining
mympd-1  | INFO     webserver       HTTP connection "6" closed
mympd-1  | DEBUG    webserver       New connection id "7" from 172.16.1.2, connections: 3
mympd-1  | INFO     webserver       HTTP request (7): GET /assets/coverimage-mympd
mympd-1  | DEBUG    webserver       Set connection 7 to is_draining
mympd-1  | INFO     webserver       HTTP connection "7" closed
mympd-1  | DEBUG    webserver       New connection id "8" from 172.16.1.2, connections: 3
mympd-1  | INFO     webserver       HTTP request (8): GET /assets/i18n/en-US.json
mympd-1  | DEBUG    webserver       Set connection 8 to is_draining
mympd-1  | INFO     webserver       HTTP connection "8" closed
mympd-1  | DEBUG    webserver       New connection id "9" from 172.16.1.2, connections: 3
mympd-1  | INFO     webserver       HTTP request (9): GET /assets/ligatures.json
mympd-1  | DEBUG    webserver       Set connection 9 to is_draining
mympd-1  | INFO     webserver       HTTP connection "9" closed
mympd-1  | DEBUG    webserver       New connection id "10" from 172.16.1.2, connections: 3
mympd-1  | INFO     webserver       HTTP request (10): POST /api/default
mympd-1  | DEBUG    webserver       "default": API request (10): {"jsonrpc":"2.0","id":729509001,"method":"MYMPD_API_SETTINGS_GET","params":{}}
mympd-1  | INFO     webserver       "default": API request (10): MYMPD_API_SETTINGS_GET
mympd-1  | DEBUG    mympdapi        Queue event
mympd-1  | DEBUG    mympdapi        Queue "mympd_api_queue": 0 entries
mympd-1  | DEBUG    mympdapi        "default": Queue event
mympd-1  | DEBUG    mympdapi        "default": Leaving mpd idle mode
mympd-1  | DEBUG    mympdapi        "default": Handle API request "MYMPD_API_SETTINGS_GET"
mympd-1  | DEBUG    mympdapi        "default": MYMPD API request (10)(729509001) MYMPD_API_SETTINGS_GET: {"jsonrpc":"2.0","id":729509001,"method":"MYMPD_API_SETTINGS_GET","params":{}}
mympd-1  | DEBUG    mympdapi        Push response to webserver queue for connection 10: {"jsonrpc":"2.0","id":729509001,"result":{"method":"MYMPD_API_SETTINGS_GET","mympdVersion":"19.0.1","mpdHost":"/run/mpd/socket","mpdPort":6600,"mpdPass":"dontsetpassword","mpdTimeout":30000,"mpdKeepalive":true,"mpdBinarylimit":262144,"stickerdbMpdHost":"/run/mpd/socket","stickerdbMpdPort":6600,"stickerdbMpdPass":"dontsetpassword","stickerdbMpdTimeout":30000,"stickerdbMpdKeepalive":true,"pin":false,"debugMode":false,"coverimageNames":"cover,folder","thumbnailNames":"cover-sm,folder-sm","loglevel":7,"smartpls":false,"smartplsSort":"","smartplsPrefix":"myMPDsmart","smartplsInterval":14400,"lastPlayedCount":2000,"musicDirectory":"auto","playlistDirectory":"auto","bookletName":"booklet.pdf","infoTxtName":"info.txt","volumeMin":0,"volumeMax":100,"volumeStep":5,"lyricsUsltExt":"txt","lyricsSyltExt":"lrc","lyricsVorbisUslt":"LYRICS","lyricsVorbisSylt":"SYNCEDLYRICS","viewHome":{"mode":"grid","fields":["Name"]},"viewSearch":{"mode":"table"...
mympd-1  | DEBUG    mympdapi        "default": Entering mpd idle mode
mympd-1  | DEBUG    webserver       Queue "web_server_queue": 0 entries
mympd-1  | DEBUG    webserver       "default": Got API response for id "10"
mympd-1  | DEBUG    webserver       "default": Sending response to conn_id "10" (length: 6327): {"jsonrpc":"2.0","id":729509001,"result":{"method":"MYMPD_API_SETTINGS_GET","mympdVersion":"19.0.1","mpdHost":"/run/mpd/socket","mpdPort":6600,"mpdPass":"dontsetpassword","mpdTimeout":30000,"mpdKeepalive":true,"mpdBinarylimit":262144,"stickerdbMpdHost":"/run/mpd/socket","stickerdbMpdPort":6600,"stickerdbMpdPass":"dontsetpassword","stickerdbMpdTimeout":30000,"stickerdbMpdKeepalive":true,"pin":false,"debugMode":false,"coverimageNames":"cover,folder","thumbnailNames":"cover-sm,folder-sm","loglevel":7,"smartpls":false,"smartplsSort":"","smartplsPrefix":"myMPDsmart","smartplsInterval":14400,"lastPlayedCount":2000,"musicDirectory":"auto","playlistDirectory":"auto","bookletName":"booklet.pdf","infoTxtName":"info.txt","volumeMin":0,"volumeMax":100,"volumeStep":5,"lyricsUsltExt":"txt","lyricsSyltExt":"lrc","lyricsVorbisUslt":"LYRICS","lyricsVorbisSylt":"SYNCEDLYRICS","viewHome":{"mode":"grid","fields":["Name"]},"viewSearch":{"mode"...
mympd-1  | DEBUG    webserver       Sending 6327 bytes to 10
mympd-1  | DEBUG    webserver       Set connection 10 to is_draining
mympd-1  | INFO     webserver       HTTP connection "10" closed
mympd-1  | DEBUG    webserver       New connection id "11" from 172.16.1.2, connections: 3
mympd-1  | INFO     webserver       HTTP request (11): GET /assets/appicon-192.png
mympd-1  | DEBUG    webserver       Set connection 11 to is_draining
mympd-1  | INFO     webserver       HTTP connection "11" closed
mympd-1  | DEBUG    webserver       New connection id "12" from 172.16.1.2, connections: 3
mympd-1  | INFO     webserver       HTTP request (12): GET /mympd.webmanifest
mympd-1  | DEBUG    webserver       Set connection 12 to is_draining
mympd-1  | INFO     webserver       HTTP connection "12" closed
mympd-1  | DEBUG    webserver       New connection id "13" from 172.16.1.2, connections: 3
mympd-1  | INFO     webserver       HTTP request (13): GET /assets/i18n/en-US.json
mympd-1  | DEBUG    webserver       Set connection 13 to is_draining
mympd-1  | INFO     webserver       HTTP connection "13" closed
mympd-1  | DEBUG    webserver       New connection id "14" from 172.16.1.2, connections: 3
mympd-1  | INFO     webserver       HTTP request (14): GET /sw.js
mympd-1  | DEBUG    webserver       Set connection 14 to is_draining
mympd-1  | INFO     webserver       HTTP connection "14" closed
mympd-1  | DEBUG    webserver       New connection id "15" from 172.16.1.2, connections: 3
mympd-1  | INFO     webserver       HTTP request (15): GET /assets/appicon-192.png
mympd-1  | DEBUG    webserver       Set connection 15 to is_draining
mympd-1  | INFO     webserver       HTTP connection "15" closed
mympd-1  | DEBUG    webserver       New connection id "16" from 172.16.1.2, connections: 3
mympd-1  | INFO     webserver       HTTP request (16): GET /sw.js
mympd-1  | DEBUG    webserver       Set connection 16 to is_draining
mympd-1  | INFO     webserver       HTTP connection "16" closed
```

https://jcorporation.github.io/myMPD/debug Doesn't work. I tried https://jcorporation.github.io/myMPD/040-debug/

 
**Configuration (please attach if it can be useful)**

- docker-compose.yaml

```
services:
  mympd:
    image: ghcr.io/jcorporation/mympd/mympd:19.0.1
    environment:
      TZ: Europe/Bucharest
      UMASK_SET: 022
      MYMPD_SSL: false
      MPD_HOST: /run/mpd/socket
      MYMPD_LOGLEVEL: 7
    volumes:
      - /var/lib/mpd/socket:/run/mpd/socket
      - /var/lib/mpd/playlists:/playlists/:ro
      - ./volumes/mympd/dir:/var/lib/mympd/
      - /media/ultrastar2/downloads/Music:/music/:ro
    restart: unless-stopped
    networks:
      traefik:
    labels:
      traefik.enable: true
      traefik.http.middlewares.mympd-csp.headers.contentSecurityPolicy: default-src 'self'; worker-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
      traefik.http.middlewares.local-auth.basicauth.users: someuser:somepassword
      traefik.http.middlewares.strip-auth.headers.customRequestHeaders.Authorization:
      traefik.http.services.mympd.loadbalancer.server.port: 80
      traefik.http.routers.mympd.entrypoints: websecure
      traefik.http.routers.mympd.rule: Host(`mympd.local.lan`)
      traefik.http.routers.mympd.tls: true
      traefik.http.routers.mympd.middlewares: filter-lan-ip-only@file,mympd-csp
      traefik.http.routers.mympd.tls.certResolver: stepca
      traefik.docker.network: docker-traefik_traefik
networks:
  traefik:
    name: docker-traefik_traefik
    external: true
```

- mpd.conf

```
user "mpd"
group "audio"
music_directory                 "/media/ultrastar2/downloads/Music"
playlist_directory "/var/lib/mpd/playlists"
db_file "/var/lib/mpd/database"
log_file "/var/log/mpd/mpd.log"
pid_file "/run/mpd/mpd.pid"
state_file "/var/lib/mpd/state"
bind_to_address "192.168.1.2"
bind_to_address "/var/lib/mpd/socket"
password                        "mypassword@read,add,control,admin"
filesystem_charset "UTF-8"
include "/etc/mpd/d3x.conf"
local_permissions "read,add,control,admin"
```

[state.tar.gz](https://github.com/user-attachments/files/18252285/state.tar.gz)
[config.tar.gz](https://github.com/user-attachments/files/18252288/config.tar.gz)

**Comment by jcorporation** [comment]
Your setting for the `startupView` is the reason of this error. It points to an old, meanwhile invalid view: `Browse/Playlists`. Simply remove `webui_settings` in `/var/lib/mympd_state` folder or remove `"startupView":"Browse/Playlists",` in this file.

**Comment by d3xt3r01** [comment]
Sounds legit.
Can this issue be treated and if the view is invalid to load Home?
Getting stuck isn't a good UX.

**Comment by jcorporation** [comment]
Some error checking for this is a good idea. I add it to the v19.1.0 milestone.
